# DeepDream Configuration

# Reproducibility
seed: 43

# Common params
input: "spock.jpeg"
img_width: 600
layers_to_use: ["relu4_3"]
model_name: "VGG16_EXPERIMENTAL"
pretrained_weights: "IMAGENET"

# Main params for experimentation
pyramid_size: 4
pyramid_ratio: 1.8
num_gradient_ascent_iterations: 5
lr: 0.09

# Params you usually won't need to change as often
should_display: false
spatial_shift_size: 32
smoothing_coefficient: 0
use_noise: false