# DeepDream Configuration

# Reproducibility
seed: 43

# Common params
input: "cloud.jpg"
img_width: 600
layers_to_use:
  # relu4_2: null
  linear3: [954]

model_name: "VGG16_EXPERIMENTAL"
pretrained_weights: "IMAGENET"

# Main params for experimentation
pyramid_size: 2
pyramid_ratio: 2
num_gradient_ascent_iterations: 100
lr: 0.09

# Params you usually won't need to change as often
spatial_shift_size: 32
smoothing_coefficient: 0.8
use_noise: false