# DeepDream Configuration

# Reproducibility
seed: 43

# Common params
input: "figures.jpg"
img_width: 600
layers_to_use:
  relu5_3: null
  # linear3: [950]

model_name: "VGG16_EXPERIMENTAL"
pretrained_weights: "IMAGENET"

# Main params for experimentation
pyramid_size: 5
pyramid_ratio: 1.8
num_gradient_ascent_iterations: 20
lr: 0.09

# Params you usually won't need to change as often
spatial_shift_size: 32
smoothing_coefficient: 1
use_noise: true